[build]
  command = "npm install --prefix train-dare-frontend && npm run build --prefix train-dare-frontend"
  publish = "train-dare-frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://dh2013-train-and-dare-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
