[build]
  command = "npm install --prefix train-dare-frontend && npm run build --prefix train-dare-frontend"
  publish = "train-dare-frontend/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
